### ISSUE TITLE
Paper should use Password Manager

### ISSUE THREAD

**Issue by Mno-hime** [yegortimoshenko/paper#18] opened 2015-08-03 07:57 UTC
I am not sure this is possible but Paper should use the Password Manager in Firefox instead of holding the password on its own. I can see that Zotero addon has an entry in the Password Manager: `chrome://zotero`. Also Paper should use "password" input field in its Settings so the password is not to be seen that easily.

**Comment by yegortimoshenko** [comment] 2015-08-03 11:34
Will do. Closing for now as a duplicate of #15.

**Closed by yegortimoshenko** 2015-08-03 11:34 UTC
